<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Users\Add.razor" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Azure.Core" Version="1.13.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.8.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.6.1" />
    <PackageReference Include="BlazorDateRangePicker" Version="3.5.0" />
    <PackageReference Include="Blazored.SessionStorage" Version="1.0.13" />
    <PackageReference Include="BlazorInputFile" Version="0.2.0" />
    <PackageReference Include="ChartJs.Blazor" Version="1.1.0" />
    <PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="5.0.5" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="5.0.8" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.11.0" />
    <PackageReference Include="MudBlazor" Version="5.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="ReviewIt.Dto" Version="1.1.25" />
  </ItemGroup>

</Project>
