<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<UserSecretsId>7d2d2843-9ea2-49ac-bb07-d4de79befae4</UserSecretsId>	
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="10.1.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" />
		<PackageReference Include="Azure.Identity" Version="1.5.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.8.0" />
		<PackageReference Include="BlazorDateRangePicker" Version="4.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.9" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.5.1" />
		<PackageReference Include="Microsoft.Azure.SignalR" Version="1.13.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.9" />
		<PackageReference Include="MudBlazor" Version="6.0.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrokerIQ.Online.Server\BrokerIQ.Online.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SyncfusionLicense.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
