<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<UserSecretsId>7d2d2843-9ea2-49ac-bb07-d4de79befae4</UserSecretsId>	
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.14.1" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.11.0" />
		<PackageReference Include="Microsoft.Azure.SignalR" Version="1.13.0" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="5.2.0" />
		<PackageReference Include="Azure.Identity" Version="1.8.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrokerIQ.Online.Server\BrokerIQ.Online.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SyncfusionLicense.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
