<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<ApplicationIcon />
		<OutputType>Library</OutputType>
		<StartupObject />
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<Version>1.1.10</Version>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Pages\Users\Add.razor" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="Azure.Core" Version="1.21.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.10.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.8.0" />
		<PackageReference Include="BlazorDateRangePicker" Version="4.0.0" />
		<PackageReference Include="Blazored.SessionStorage" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="7.0.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.15.0" />
		<PackageReference Include="MudBlazor" Version="6.0.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="BrokerIQ.Dto" Version="1.0.69" />
		<PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
	</ItemGroup>


	<ItemGroup>
	  <Content Update="wwwroot\js\AudioRecord.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
