<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
	</PropertyGroup>

	  <ItemGroup>
    <Content Remove="appsettings.json" />
	  <Content Remove="C:\Users\Livingroom\.nuget\packages\chartjs.blazor.fork\2.0.2\contentFiles\any\netstandard2.1\wwwroot\ChartJsBlazorInterop.js" />
    <Content Remove="wwwroot\js\AudioRecord.js" />
    <Content Remove="wwwroot\js\Autologout.js" />
    <Content Remove="wwwroot\js\Microphone.js" />
    <Content Remove="wwwroot\js\openInTab.js" />
    <Content Remove="wwwroot\js\saveAsFile.js" />
  </ItemGroup>

  <ItemGroup>
	  <None Include="wwwroot\js\AudioRecord.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\Autologout.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\Microphone.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\openInTab.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\saveAsFile.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrokerIQ.Online.Server\BrokerIQ.Online.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SyncfusionLicense.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	

  <ItemGroup>
    <Content Update="Shared\NavMenu.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\appsettings.development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\appsettings.development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon-alert.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>	

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>
</Project>
