<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
	  <Version>1.0.26</Version>
	</PropertyGroup>

	  <ItemGroup>
    <Content Remove="appsettings.json" />
	  <Content Remove="C:\Users\Livingroom\.nuget\packages\chartjs.blazor.fork\2.0.2\contentFiles\any\netstandard2.1\wwwroot\ChartJsBlazorInterop.js" />
    <Content Remove="wwwroot\js\AudioRecord.js" />
    <Content Remove="wwwroot\js\Autologout.js" />
    <Content Remove="wwwroot\js\Microphone.js" />
    <Content Remove="wwwroot\js\openInTab.js" />
    <Content Remove="wwwroot\js\saveAsFile.js" />
  </ItemGroup>

  <ItemGroup>
	  <None Include="C:\Users\Livingroom\.nuget\packages\chartjs.blazor.fork\2.0.2\contentFiles\any\netstandard2.1\wwwroot\ChartJsBlazorInterop.js">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Include="wwwroot\js\AudioRecord.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\Autologout.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\Microphone.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\openInTab.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="wwwroot\js\saveAsFile.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
		
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="Azure.Core" Version="1.21.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.10.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.8.0" />
		<PackageReference Include="BlazorDateRangePicker" Version="4.0.0" />
		<PackageReference Include="Blazored.SessionStorage" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="7.0.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.15.0" />
		<PackageReference Include="MudBlazor" Version="6.0.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="BrokerIQ.Dto" Version="1.0.62" />
		<PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
		<PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />	
		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BrokerIQ.Online.Server\BrokerIQ.Online.Server.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="SyncfusionLicense.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	

  <ItemGroup>
    <Content Update="Shared\NavMenu.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\appsettings.development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\appsettings.development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon-alert.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>	

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
